apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: metis-cluster
servers: 1
agents: 1
volumes:
  - volume: /tmp/metis-k3d-objects:/var/lib/metis/objects
    nodeFilters:
      - server:*
      - agent:*
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
