"""support asynchronous jobs

Revision ID: 3a8f6be59e66
Revises: f69c465aa448
Create Date: 2026-10-01 07:15:46.683673
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a8f6be59e66"
down_revision: str | None = "f69c465aa448"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingestion_jobs",
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "ingestion_jobs", "document_version_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_unique_constraint(
        "uq_ingestion_job_idempotency",
        "ingestion_jobs",
        ["organisation_id", "idempotency_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ingestion_job_idempotency", "ingestion_jobs", type_="unique")
    op.alter_column(
        "ingestion_jobs", "document_version_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("ingestion_jobs", "idempotency_key")
    # ### end Alembic commands ###
